### ISSUE TITLE
Error with SimpleSAMLphp

### ISSUE THREAD

**Issue by RealKoenisch** [hvirring/simplesamlphp-sqlauthbcrypt#6]
I got the following error when using this modul with SimpleSAMLphp V2.2.1.

SimpleSAML\Error\Error: UNHANDLEDEXCEPTION
Backtrace:
2 src/SimpleSAML/Error/ExceptionHandler.php:32 (SimpleSAML\Error\ExceptionHandler::customExceptionHandler)
1 vendor/symfony/error-handler/ErrorHandler.php:535 (Symfony\Component\ErrorHandler\ErrorHandler::handleException)
0 [builtin] (N/A)
Caused by: Exception: sqlauthBcrypt:bcrypt-example: - Failed to execute query: SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens
Backtrace:
8 modules/sqlauthbcrypt/src/Auth/Source/SQL.php:174 (SimpleSAML\Module\sqlauthbcrypt\Auth\Source\SQL::login)
7 modules/core/src/Auth/UserPassBase.php:305 (SimpleSAML\Module\core\Auth\UserPassBase::handleLogin)
6 modules/core/src/Controller/Login.php:215 (SimpleSAML\Module\core\Controller\Login::handleLogin)
5 modules/core/src/Controller/Login.php:114 (SimpleSAML\Module\core\Controller\Login::loginuserpass)
4 vendor/symfony/http-kernel/HttpKernel.php:181 (Symfony\Component\HttpKernel\HttpKernel::handleRaw)
3 vendor/symfony/http-kernel/HttpKernel.php:76 (Symfony\Component\HttpKernel\HttpKernel::handle)
2 vendor/symfony/http-kernel/Kernel.php:197 (Symfony\Component\HttpKernel\Kernel::handle)
1 src/SimpleSAML/Module.php:234 (SimpleSAML\Module::process)
0 public/module.php:17 (N/A)

KR

**Comment by hvirring** [comment]
Unfortunately I do not have a working setup with SimpleSAMLphp V2.2.1, but you're welcome to submit a PR with a fix and I'll be happy to merge it.

**Comment by RealKoenisch** [comment]
Thanks for your response, but I am very new in simplesaml and have honestly spoken no glue of the structure of the programm. So I won't be very helpfull. I solved the problem with the lastes Version of sqlauth which can handle with the parameter PasswordVerify bcrypt as well.

**Comment by hvirring** [comment]
Great to hear you solved it! I'll close this issue then.

**Comment by RealKoenisch** [comment]
I found a workaround I have added the changes in the repository. It seems that the newer version checks the amount of parameters in a query.

**Comment by hvirring** [comment]
Thanks, I just merged your PR.
